spring:
  # R2DBC Configuration
  r2dbc:
    url: 'r2dbc:pool:postgres://8.152.158.64:5432/ssc?stringtype=unspecified'
    username: 'postgres'
    password: 'not4u2day'
  # Redis Configuration
  data:
    redis:
      host: '43.143.100.78'
      port: 6379
      database: 0
      password: 'OW9wXPFyUoADWP2h'
